name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: squashfuse-static
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo sh -c 'apt update && apt install qemu-user-static -y'

      - name: Build x86_64 musl
        run: |
            docker run --rm -v "${{ github.workspace }}:/root" --platform=linux/amd64 alpine:latest /root/build.sh

      - name: Build aarch64 musl
        run: |
            docker run --rm -v "${{ github.workspace }}:/root" --platform=linux/arm64 alpine:latest /root/build.sh

      - name: Rename musl
        run: |
            shopt -s extglob
            for bin in $(ls release/!(*glibc*|*musl*))
                do mv "$bin" release/"$(basename "$bin"|sed 's|squashfuse|squashfuse-musl|')"
            done

      - name: Build x86_64 glibc
        run: |
            docker run --rm -v "${{ github.workspace }}:/root" --platform=linux/amd64 ubuntu:jammy bash /root/build.sh

      - name: Build aarch64 glibc
        run: |
            docker run --rm -v "${{ github.workspace }}:/root" --platform=linux/arm64 ubuntu:jammy bash /root/build.sh

      - name: Rename glibc
        run: |
            shopt -s extglob
            for bin in $(ls release/!(*glibc*|*musl*))
                do mv "$bin" release/"$(basename "$bin"|sed 's|squashfuse|squashfuse-glibc|')"
            done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
